site_name: Erie Looking Productions
theme: mkdocs
site_url: https://erielookingproductions.info/
site_description: The primary public-facing website of Erie Looking Productions
site_author: Stephen Michael Kellat
copyright: Copyright Â© 2019-2022 Erie Looking Productions and Stephen Michael Kellat.  
plugins: []
nav:
     - Home: index.md
     - What We Do: services.md
     - Works: wip.md
     - Wartime: statement.md
